name: leto_schema
version: 0.0.1-dev.3
description: An implementation of GraphQL's type system in Dart. Basis of leto.
repository: https://github.com/juancastillo0/leto

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.16.0
  gql: ^1.0.0
  meta: ^1.0.0
  source_span: ^1.0.0

dev_dependencies:
  leto:
  lint: ^2.1.2
  test: ^1.0.0

dependency_overrides:
  leto:
    path: ../leto
