name: leto_shelf
description: Build GraphQL web servers with leto and shelf.
version: 0.0.1-dev.1
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  freezed_annotation: ^2.0.0
  gql: ^0.14.0
  http_parser: ^4.0.0
  http_server: ^1.0.0
  json_annotation: ^4.7.0
  leto: ^0.0.1-dev.1
  leto_schema: ^0.0.1-dev.3
  mime: ^1.0.2
  oxidized: ^5.2.0
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.4
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: 2.0.3
  gql_exec: ^0.4.0
  gql_link: ^0.5.0
  gql_websocket_link: ^0.3.3
  http: ^0.13.3
  json_serializable: ^6.2.0
  lint: ^1.0.0
  test: ^1.0.0
  toml: ^0.12.0
