name: leto_shelf
description: Build GraphQL web servers with leto and shelf.
version: 0.0.1-dev.1
homepage: https://github.com/juancastillo0/leto

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto:
  freezed_annotation:
  gql:
  http_parser:
  http_server:
  json_annotation:
  leto: ^0.0.1-dev.1
  leto_schema: ^0.0.1-dev.3
  mime:
  oxidized:
  shelf:
  shelf_web_socket:
  web_socket_channel:

dev_dependencies:
  build_runner:
  freezed:
  gql_exec:
  gql_link:
  gql_websocket_link:
  http:
  json_serializable:
  lint:
  test:
  toml:

dependency_overrides:
  leto: 
    path: ../leto
  leto_schema:
    path: ../leto_schema